[package]
name = "paxos"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1", features = ["full"] }
bytes = "1.2"
log = "0.4"

[build-dependencies]
tonic-build = "0.8"
